CREATE TABLE "GCG_5957_MAINT"(
 "REC_ID" IDENTITY DEFAULT '0',
 "RB_DATABASE" CHAR(50),
 "LAST_ORD_REC" INTEGER,
 "REC_NAME" CHAR(50),
 "REC_EMAIL" CHAR(50),
 "LAST_PID" INTEGER,
 "LAST_RUN_TIME" DATETIME,
 UNIQUE ("REC_ID"));